const fs = require('fs');

const ac_raw = `
CMBT: CMBT, MMDA, VADAPALANI
MANALI NEW TOWN: MANALI NEW TOWN, CPCL, MANALI MARKET, MATHUR, MILK COLONY, ARUL NAGAR, POST OFFICE
ASHOK PILLAR: ASHOK PILLAR, KASI THEATRE, EKKATU THANGAL
THIRUVOTTIYUR: THIRUVOTTIYUR, N-4, KASIMEDU SIGNAL
PARRYS: PARRYS CORNER, KANNAGI STATUE, MRC NAGAR, SRP TOOLS, PERUNGUDI
KK NAGAR DEPOT: KK NAGAR DEPOT, SIVANPARK
NATHAMUNI: NATHAMUNI, K4 POLICE STATION, 18TH MAIN ROAD
MADHYAKAILASH: MADHYAKAILASH, MADIPAKKAM KOOT ROAD
AYANAVARAM: AYANAVARAM, ESI HOSPITAL, MEDAVAKKAM TANK ROAD, SECRETARIAT COLONY, KELLYS, MUMMY DADY BUS STAND, KILPAUK GARDEN
NATRAJA THEATERE: NATRAJA THEATERE, CHENNAI CORPORATION (RIPON BUILDING), PANTHEON ROAD ( EGMORE RAMADA HOTEL )
KOLATHUR: KOLATHUR PERTOL BUNK, WELDING SHOP
AVICHI SCHOOL: AVICHI SCHOOL
STERLING ROAD: NELSON MANICKAM ROAD, POTHYS(T.NAGAR)
TRIPLICANE: TRIPLICANE, ROYAPETTAH
BESANT NAGAR: BESANT NAGAR BUS STAND, VANNANTHURAI BUS STAND, VETTUVANKENI CHRUCH, AKKARI
VGP: VGP, PERUMBAKKAM, MEDAVAKKAM
AMINJIKARAI: AMINJIKARAI, SKYWALK
AMBEDKAR NAGAR: AMBEDKAR NAGAR, RETTERI
KALIAMMAN KOIL MAIN ROAD: KALIAMMAN KOIL MAIN ROAD (KOYEMBEDU MARKET), VIRUGAMBAKKAM SIGNAL
KANCHIPURAM: KANCHIPURAM, WALAJABAD, ORAGADAM
ALANDUR METRO: ALANDUR METRO, NANGANALLUR PETROL BUNK, MEENAMBAKKAM, PALLAVARAM
METHA NAGAR: METHA NAGAR, ANAGAPUTHUR BUS STAND, RETTAI PILLAIYAR KOVIL PAMMAL
LIGHT HOUSE: LIGHT HOUSE, ALL INDIA RADIO, KANDANCHAVADI
THATHANKUPPAM: THATHANKUPPAM, ANNA NAGAR WEST DEPOT, ROHINI THEATRE, MADURAVOYAL ERIKARAI
ICF: ICF, PADI SARAVANA STORES, AMBATTUR INDUSTRIAL ESTATE
VALASARAVAKKAM: VALASARAVAKKAM
AMBATTUR ORAGADAM: AMBATTUR ORAGADAM, AMBATTUR OT
DEVAR STATUE: DEVAR STATUE (NANDANAM JUNCTION), VELACHERY 100 FT ROAD, VELACHERY VIJAYANAGAR
MADIPAKKAM KEELKATALAI: KEELKATALAI, ECHANGADU SIGNAL, KOVILAMBAKKAM
PADI EAST AVENUE: PADI EAST AVENUE, MANIKANDAPURAM BUS STAND, THIRUMULLAIVOYAL BUS STAND, VAISNAVINAGAR
THIRUMANGALAM: THIRUMANGALAM, WAVES
DAGAC: DAGAC (AMBEDKAR COLLEGE), SHARMA NAGAR, ERUKKANCHERY, KANGACHATHIRAM, KALPANA
PURASAIWALKAM: PURASAIWALKAM TANK, GENGU REDDY SUB WAY, CHETPET, VALLUVAR KOTTAM
REDHILLS: REDHILLS, KAVANKARAI, PUZHAL CAMP, KALIKUPPAM, PUDHUR
MANDAVELI: MANDAVELI, KALIYAPPA HOSPITAL, MOOPANAR BRIDGE
MADIPAKKAM: RAM NAGAR, UTI BANK
RAMAPURAM JUNCTION: RAMAPURAM JUNCTION, DLF
PERAMBUR: PERAMBUR RAILWAY STATION, PERAMBUR CHURCH, KOLATHUR JUNCTION NEAR VINAYGAR TEMPLE
PATTABIRAM: HINDU COLLEGE, PATTABIRAM, NEMILICHERY
POWER HOUSE: POWER HOUSE, SAMIYAR MADAM, WEST MAMBALAM
AVADI: MURUGAPPA POLYTECHNIC COLLEGE, AVADI, GOVARDANAGIRI, PARIVAKKAM SIGNAL
GUINDY: GUINDY RACE COURCE, NGO COLONY
SANTHOME: SANTHOME, PATINAPAKKAM, SATHYA STUDIOS, NEELANGARAI, INJAMBAKKAM
THIRUVALLUR: THIRUVALLUR BUS STAND, PUTTLUR, SEVAPATET, VEPPAMPATTU RLY., THIRUNINDRAVUR, JAYA SCHOOL BUS STOP
THIRUVANMIYUR: THIRUVANMIYUR, THIRUVANMIYUR RTO
COLLECTOR NAGAR: COLLECTOR NAGAR, JJ NAGAR POLICE STATION, 7H BUS DEPOT, 7M BUS DEPOT
THILLAI GANGA NAGAR SUBWAY: THILLAI GANGA NAGAR SUBWAY, VANUVAMPET CHURCH
GOLDEN FLATS: GOLDEN FLATS, WAVIN
ADAMBAKKAM POLICE BOOTH: ADAMBAKKAM POLICE BOOTH
THIRUVERKADU ARCH: THIRUVERKADU ARCH, NOLAMBUR, VELAMMAL HALL
KALPAKKAM: KALPAKKAM, ANUPURAM, MAHABALIPURAM KOOT ROAD(POONCHERY), THANDALAM, THIRUPORUR
CHENGALPATTU: CHENGALPATTU (GOVT. HOSPITAL), PARANUR TOLLGATE, SP KOIL
NOLAMBUR: NOLAMBUR
CHINTHAMANI: CHINTHAMANI, BLUE STAR, SHANTHI COLONY, ANNA ARCH
MAHINDRA CITY: MAHINDRA CITY, KATTANKOLATHUR, MARAIMALAI NAGAR
PORUR SARAVANA STORE: PORUR SARAVANA STORE, PORUR JUNCTION
AYODHYA MANDAPAM: AYODHYA MANDAPAM, VELACHERY RAILWAY STATION
KUTCHERY ROAD: KUTCHERY ROAD, LUZ, MYLAPORE TANK, MANDAVELI BSNL OFFICE
ADYAR AAVIN: ADYAR AAVIN, ADYAR TELEPHONE EXCHANGE, PTC QUARTERS
IYYAPANTHANGAL BUS STAND: IYYAPANTHANGAL BUS STAND, IYYAPANTHANGAL HYUNDAI SHOWROOM, KATTUPAKKAM, KUMMANACHAVADI (DMART)
AMMA NANA: KOTTURPURAM, THORAIPAKKAM, KARAPAKKAM
VANAGARAM: VANAGARAM, POONAMALLEE BYPASS
MADHANANDAPURAM: MADHANANDAPURAM
KALMANDAPAM: KALMANDAPAM, BEACH STATION, SECRETARIAT, THIRUVANMIYUR JAYANTHI
AYAPAKKAM JUNCTION: AYAPAKKAM JUNCTION, AMBATTUR TELEPHONE EXACHANGE, DECLATHON
TTK ROAD: TTK ROAD, ALWARPET JUNCTION
MOOLAKADAI: MOOLAKADAI, MADHAVARAM ROUNDTANA
MADIPAKKAM POONNIAMMAN KOIL: POONNIAMMAN KOIL
MANGADU: MANGADU, KOVUR, KUNDRATHUR, DMART, MADHA COLLEGE, THIRUMUDIVAKKAM
DAILY THANTHI: DAILY THANTHI, DASAPRAKASH, ARUMBAKKAM, NERKUNDRAM
KOTTIVAKKAM: KOTTIVAKKAM, PALAVAKKAM, MGM, KOVALAM
MUGALIVAKKAM: MUGALIVAKKAM, GERUGAMBAKKAM, THIRUNEERMALAI
SRIPERUMBUDUR: SRIPERUMBUDUR, IRUNGATTUKOTTAI, PAPPANCHATHIRAM, CHEMBARAMBAKKAM, NAZARATHPETTAI
SHOLINGANALLUR: SHOLINGANALLUR, SEMMANCHERI, NAVALUR, MARINA MALL
GANDHIMANDAPAM: GANDHIMANDAPAM, PHOENIX MALL, VELACHERY 100 FEET ROAD
NANGANALLUR: NANGANALLUR J.K MAHAL, NANGANALLUR PARK
SENTHIL NAGAR: SENTHIL NAGAR
RADIANCE APT.: RADIANCE APT., KAMATCHI HOSPITAL, S KOLATHUR, KAUVERY HOSPITAL, CHROMPET
PORUR BAIKADAI: PORUR BAIKADAI
VINAYAGAPURAM: VINAYAGAPURAM, PORUR TOLL PLAZA
`;

const non_ac_raw = `
RAJAKILPAKKAM: RAJAKILPAKKAM, SUDHARSHAN NAGAR, KOZHIPANNAI
MADRAS CHRISTIAN COLLEGE: MCC COLLEGE, BHARATH UNIVERSITY
IRUMBULIYUR: IRUMBULIYUR, SSM NAGAR, NEDUKUNDRAM TVS
RAJENDRA PRASAD ROAD: RAJENDRA PRASAD ROAD, SELIYUR POLICE STATION
VARATHARAJAN THEATRE: VARATHARAJAN THEATRE, MAPPEDU
SEMBAKKAM: SEMBAKKAM, KAMARAJAPURAM, MADAMBAKKAM JUNCTION
BALAJI DENTAL COLLEGE: BALAJI DENTAL COLLEGE
KAIVELI: KAIVELI JUNCTION, CHITALAPAKKAM, CHITALAPAKKAM KOOT ROAD, MEDAVAKKAM MAMBAKKAM JUNCTION
DLF APTS: DLF APTS, SITHALAPAKKAM KOOT ROAD
TAMBARAM RAILWAY STATION: TAMBARAM RAILWAY STATION - WEST, PERUNGALATHUR, VANDALUR
VELACHERY RAILWAY STATION: VELACHERY RAILWAY STATION (NEAR KAIVELI)
POTHERI: POTHERI, GUDUVANCHERY, URAPAKKAM, KILAMBAKKAM, KOLAPKKAM, KANDIGAI
VIJAYANAGARAM: VIJAYANAGARAM, SANTOSAHPURAM, PUTHU KOVIL, MEDAVAKKAM KOOT ROAD, SBIOA
MUDICHUR: MUDICHUR (ATTA COMPANY)
LAKSHMIPURAM: LAKSHMIPURAM, HINDU MISSION HOSPITAL, PEERKANKARANAI
PALLIKARANAI JEYACHANDRAN: PALLIKARANAI JEYACHANDRAN, KALISWARY OIL MILL, MEDAVAKKAM
BOLLINENI HILLS: BOLLINENI HILLS
MAHALAKSHMI NAGAR: MAHALAKSHMI NAGAR, CAMP ROAD
PADUR: PADUR, KELAMBAKKAM JUNCTION, PUDUPAKKAM, MAMBAKKAM
PADAPAI: PADAPAI, KARASANGAL, MANIVAKKAM JUNCTION
`;

function parseRaw(rawStr, type) {
    return rawStr.trim().split('\n').filter(l => l.trim()).map(line => {
        const [route, points] = line.split(':');
        return {
            id: type.toLowerCase() + '-' + route.trim().replace(/\s+/g, '-').toLowerCase(),
            type: type,
            route: route.trim(),
            boardingPoints: points.split(',').map(p => p.trim()),
            driverPhone: '',
            driverName: '',
            whatsappGroup: '',
            busLocation: ''
        };
    });
}

const buses = [
    ...parseRaw(ac_raw, 'AC'),
    ...parseRaw(non_ac_raw, 'Non-AC')
];

fs.writeFileSync('src/data/dayscholar_buses.json', JSON.stringify(buses, null, 2));
console.log('Saved src/data/dayscholar_buses.json with ' + buses.length + ' routes');
